version: '2'
services:
  nginx:
    image: nginx:1.12
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app
    links:
      - phpfpm

  phpfpm:
    image: php:7.1-fpm
    volumes:
      - .:/var/www/app
    ports:
      - 9000